# Override file for production use.
# Based on docker-compose.yml but overrides specific settings.
version: "3.8"

services:
  db:
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env.prod

  backend:
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - 5000
    restart: always
    env_file:
      - ./.env.prod

  frontend:
    expose:
      - 3000
    restart: always
    env_file:
      - ./.env.prod

  reverseproxy:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data_prod:
