# Override file for production use.
# Based on docker-compose.yml but overrides specific settings.
version: "3.8"

services:
  db:
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env.prod

  backend:
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - 5000
    restart: always
    env_file:
      - ./.env.prod

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_SERVER_NAME: ${SERVER_NAME}
        REACT_APP_IS_DEV_MODE: 0
    command: npm run build
    expose:
      - 3000
    volumes:
      - static_data:/usr/src/frontend/build
    env_file:
      - ./.env.prod

  reverseproxy:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_data:/build
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data_prod:
  static_data:
