name: Python CI autopep8 Flake8

on:
  push:
    branches: [main, CI-new]
  pull_request:
    branches: [main, CI-new]

jobs:
  build_pycodestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install backend/requirements_dev.txt

      - name: Check code with pycodestyle
        run: |
          pycodestyle backend

  build_flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install backend/requirements_dev.txt

      - name: Lint with Flake8
        run: |
          flake8 backend
