name: Python CI autopep8 Flake8

on:
  push:
    branches: [main, test-build]
  pull_request:
    branches: [main]

jobs:
  build_pycodestyle:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements_dev.txt

      - name: Check code with pycodestyle
        run: |
          pycodestyle --ignore=E266,W503 backend

  build_flake8:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements_dev.txt

      - name: Lint with Flake8
        run: |
          flake8 --ignore=E266,W503 backend
