name: CI ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: npm install -g eslint eslint-config-airbnb eslint-config-prettier eslint-plugin-import eslint-plugin-jsx-ally eslint-plugin-prettier eslint-plugin-react eslint-plugin-react-hooks
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx