name: CI ESLint Prettier
on:
  push:
    branches: [main, test-build]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest, windows-latest, macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint/Prettier
        run: ./node_modules/.bin/eslint . --ext .js,.jsx --no-error-on-unmatched-pattern
