name: JS CI Test
on:
  push:
    branches: [main, test-build]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run test suite
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker images
        run: docker-compose build

      - name: Build react app
        run: docker-compose run --rm frontend npm run build

      - name: Run tests
        run: docker-compose run frontend jest
