name: JS CI Test
on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      REACT_APP_MODE: dev
      REACT_APP_SERVER_NAME: localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker images
        run: docker-compose build

      - name: Build react app
        run: docker-compose run --rm frontend npm run build

      - name: Run tests
        run: docker-compose run -e CI=true frontend npm test -- --testPathIgnorePatterns performance.test.js
        env:
          REACT_APP_MODE: dev
          REACT_APP_SERVER_NAME: localhost
