# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI Test

on:
  push:
    branches: [main, ci-pytest-docker] # FIXME remove
  pull_request:
    branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 3.9
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r backend/requirements_dev.txt
#       - name: Test with pytest
#         run: |
#           pytest backend/Test/test_file.py

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Login to DockerHub
      #   run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build docker images
        run: docker-compose build

      - name: Run tests
        run: |
          ls
          docker-compose run backend python -m pytest ./test/ -s
