# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI Test

on:
  push:
    branches: [main, test-build]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest, windows-latest, macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker images
        run: docker-compose build -f docker-compose-backend.test.yml

      - name: Run tests
        run: docker-compose run backend python -m pytest ./Test/ -s
